# Create a decision tree classification model for fish.csv dataset. Display confusion matrix,accuracy score, error rate,classification report

In [6]:
#step-1: load dataset
import pandas as pd
df=pd.read_csv("fish.csv")
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


,Species,Weight,Length1,Length2,Length3,Height,Width
0,Bream,242.0,23.2,25.4,30.0,11.5200,4.0200
1,Bream,290.0,24.0,26.3,31.2,12.4800,4.3056
2,Bream,340.0,23.9,26.5,31.1,12.3778,4.6961
3,Bream,363.0,26.3,29.0,33.5,12.7300,4.4555
4,Bream,430.0,26.5,29.0,34.0,12.4440,5.1340
...,...,...,...,...,...,...,...
154,Smelt,12.2,11.5,12.2,13.4,2.0904,1.3936
155,Smelt,13.4,11.7,12.4,13.5,2.4300,1.2690
156,Smelt,12.2,12.1,13.0,13.8,2.2770,1.2558
157,Smelt,19.7,13.2,14.3,15.2,2.8728,2.0672


In [7]:
#step-2: define x and y
x=df.iloc[:,1:]
y=df.iloc[:,0]

In [8]:
#step-3: split the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
#step-4: import model
#step-5: fit or train model, get depth of tree
from sklearn.tree import DecisionTreeClassifier
d_tree=DecisionTreeClassifier(criterion="entropy",max_depth=11)
m=d_tree.fit(x_train,y_train)
print(d_tree.get_depth())

11


In [24]:
#step-6: predict y for x_test
y_pred=d_tree.predict(x_test)

In [25]:
#step-7: evaluate the model
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("TN:",cm[0][0])
print("FP:",cm[0][1])
print("FN:",cm[1][0])
print("TP:",cm[1][1])
print("accuracy:",accuracy_score(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

[[10  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0]
 [ 0  0  4  0  5  0  0]
 [ 0  0  1  2  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  1  0  0  4  0]
 [ 1  1  1  0  0  0  0]]
TN: 10
FP: 0
FN: 0
TP: 1
accuracy: 0.65625
classification report: 
               precision    recall  f1-score   support

       Bream       0.91      1.00      0.95        10
      Parkki       0.50      1.00      0.67         1
       Perch       0.50      0.44      0.47         9
        Pike       1.00      0.67      0.80         3
       Roach       0.00      0.00      0.00         1
       Smelt       1.00      0.80      0.89         5
   Whitefish       0.00      0.00      0.00         3

    accuracy                           0.66        32
   macro avg       0.56      0.56      0.54        32
weighted avg       0.69      0.66      0.66        32



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


## KNN

In [41]:
import pandas as pd
df=pd.read_csv("fish.csv")
print(df.info())
print(df)

x=df.iloc[:,1:]
y=df.iloc[:,0]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,
                                                 random_state=42)
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=13)
m=knn.fit(x_train,y_train)

y_pred=knn.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("accuracy:",accuracy_score(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB
None
    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


# Random Forest Classifier

In [40]:
import pandas as pd
df=pd.read_csv("fish.csv")
# print(df.info())

x=df.iloc[:,1:]
y=df.iloc[:,0]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,
                                                 random_state=42)

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=42,max_depth=10)
m=rf.fit(x_train,y_train)

y_pred=rf.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("accuracy:",accuracy_score(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

[[10  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0]
 [ 0  0  6  0  3  0  0]
 [ 0  0  0  3  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  1  0  2  0  0]]
accuracy: 0.78125
classification report: 
               precision    recall  f1-score   support

       Bream       1.00      1.00      1.00        10
      Parkki       1.00      1.00      1.00         1
       Perch       0.75      0.67      0.71         9
        Pike       1.00      1.00      1.00         3
       Roach       0.00      0.00      0.00         1
       Smelt       1.00      1.00      1.00         5
   Whitefish       0.00      0.00      0.00         3

    accuracy                           0.78        32
   macro avg       0.68      0.67      0.67        32
weighted avg       0.80      0.78      0.79        32



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [37]:
import pandas as pd
df=pd.read_csv("iris.csv")
df.info()
df

x=df.iloc[:,1:-1]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,
                                                 random_state=42)

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=42,max_depth=10)
m=rf.fit(x_train,y_train)

y_pred=rf.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("accuracy:",accuracy_score(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
TN: 10
FP: 0
FN: 0
TP: 9
accuracy: 1.0
classification report: 
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00 

## PB 227:

In [43]:
df=pd.read_csv("insurance.csv")
df.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [46]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]
x=pd.get_dummies(x,drop_first=True)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,
                                                 random_state=42)
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

m=model.coef_
c=model.intercept_
print("co-efficient: \n",m)
print("Intercept: \n",c)

from sklearn.metrics import mean_squared_error,r2_score
print("MSE:",mean_squared_error(y_test,y_pred))
print("r2Score:",r2_score(y_test,y_pred))

co-efficient: 
 [ 2.56975706e+02  3.37092552e+02  4.25278784e+02 -1.85916916e+01
  2.36511289e+04 -3.70677326e+02 -6.57864297e+02 -8.09799354e+02]
Intercept: 
 -11931.219050326674
MSE: 33596915.851361446
r2Score: 0.7835929767120724


# Support Vector Machine

In [5]:
import pandas as pd
df=pd.read_csv("diabetes.csv")
print(df.info())

x=df.iloc[:,0:8]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.svm import SVC
svm_model=SVC(kernel="rbf",random_state=42,C=10)
#C: regulazitaion parameter of C will increase margin distance & reduce error 
#it may go in overfitting
#Low value of C will decrease marginal distance & reduce accuracy
#kernel will convert dataset from higher dimension to make it separable
#rbf: radial bias function, most powerfull & commonly used
svm_model.fit(x_train,y_train)

y_pred=svm_model.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("TN:",cm[0][0])
print("FP:",cm[0][1])
print("FN:",cm[1][0])
print("TP:",cm[1][1])
print("accuracy:",accuracy_score(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None
[[83 16]
 [20 35]]
TN: 83
FP: 16
FN: 20
TP: 35
accuracy: 0.7662337662337663
classification report: 
               precision    recall  f1-score   support

           0       0.81      0.84      0.82        99
           1       0.69  

# 9 marks program:

In [34]:
# Data Preprocessing
import pandas as pd
df=pd.read_csv("Employee_Attrition.csv")
df.info()
df=df.drop("Employee_ID",axis=1)
df=pd.get_dummies(df,drop_first=True,dtype="int")
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Employee_ID         250 non-null    int64 
 1   Age                 250 non-null    int64 
 2   Monthly_Income      250 non-null    int64 
 3   Years_at_Company    250 non-null    int64 
 4   Job_Role            250 non-null    object
 5   Work_Life_Balance   250 non-null    object
 6   Overtime            250 non-null    object
 7   Job_Satisfaction    250 non-null    int64 
 8   Distance_From_Home  250 non-null    int64 
 9   Education           250 non-null    object
 10  Attrition           250 non-null    int64 
dtypes: int64(7), object(4)
memory usage: 21.6+ KB
     Age  Monthly_Income  Years_at_Company  Job_Satisfaction  \
0     29           23278                 8                 1   
1     56           31395                18                 1   
2     54           98907    

In [37]:
#KNN
x=df.drop("Attrition",axis=1)
y=df["Attrition"]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,
                                               random_state=42)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
acc_list=[]
for k in range(1,26):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    y_pred=knn.predict(x_test)
    acc=accuracy_score(y_test,y_pred)
    acc_list.append(acc)
    print(f"k={k},Accuracy={acc}")

max_acc=max(acc_list)
best_k=(acc_list.index(max_acc))+1
print("best k:",best_k)
knn=KNeighborsClassifier(n_neighbors=best_k)
knn.fit(x_train,y_train)

k=1,Accuracy=0.86
k=2,Accuracy=0.94
k=3,Accuracy=0.94
k=4,Accuracy=0.94
k=5,Accuracy=0.94
k=6,Accuracy=0.94
k=7,Accuracy=0.94
k=8,Accuracy=0.94
k=9,Accuracy=0.94
k=10,Accuracy=0.94
k=11,Accuracy=0.94
k=12,Accuracy=0.94
k=13,Accuracy=0.94
k=14,Accuracy=0.94
k=15,Accuracy=0.94
k=16,Accuracy=0.94
k=17,Accuracy=0.94
k=18,Accuracy=0.94
k=19,Accuracy=0.94
k=20,Accuracy=0.94
k=21,Accuracy=0.94
k=22,Accuracy=0.94
k=23,Accuracy=0.94
k=24,Accuracy=0.94
k=25,Accuracy=0.94
best k: 2


,n_neighbors,2
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [38]:
#random forest
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=150,random_state=42,
                          max_depth=12)
m=rf.fit(x_train,y_train)

y_pred1=rf.predict(x_test)
acc=accuracy_score(y_test,y_pred1)
print("accuracy of RF:",acc)
cm=confusion_matrix(y_test,y_pred1)
print("cm for RF: \n",cm)

accuracy of RF: 0.98
cm for RF: 
 [[47  0]
 [ 1  2]]


In [39]:
#Prediction Task
import numpy as np
x_t=np.array([30,45000,5,3,10,1,0,0,1,0,1,0,0]).reshape(1,-1)
print(x_t)
print("prediction for knn model:",knn.predict(x_t))
print("prediction for Rf model:",rf.predict(x_t))

[[   30 45000     5     3    10     1     0     0     1     0     1     0
      0]]
prediction for knn model: [0]
prediction for Rf model: [0]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [41]:
# SVM
from sklearn.svm import SVC
svm=SVC(kernel="rbf",random_state=42,C=10)
svm.fit(x_train,y_train)
y_pred2=svm.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred2)
print(cm)
print("TN:",cm[0][0])
print("FP:",cm[0][1])
print("FN:",cm[1][0])
print("TP:",cm[1][1])
print("accuracy:",accuracy_score(y_test,y_pred2))
print("classification report: \n",classification_report(y_test,y_pred2))

[[47  0]
 [ 3  0]]
TN: 47
FP: 0
FN: 3
TP: 0
accuracy: 0.94
classification report: 
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        47
           1       0.00      0.00      0.00         3

    accuracy                           0.94        50
   macro avg       0.47      0.50      0.48        50
weighted avg       0.88      0.94      0.91        50



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
